# Generated by Django 5.2.10 on 2026-02-02 06:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0002_blockedip_requestlog_city_requestlog_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
